### ISSUE TITLE
Show which version of aqua is installed when installing

### ISSUE THREAD

**Issue by tadayosi** [aquaproj/aqua-installer#168]
Right now when you run aqua-installer it only tells the progress and location to be installed. Is it possible to show which version is going to be installed as well?
```
$ aqua-installer 
===> Downloading https://github.com/aquaproj/aqua/releases/latest/download/aqua_linux_amd64.tar.gz ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5651k  100 5651k    0     0  3255k      0  0:00:01  0:00:01 --:--:-- 10.1M
===> Install aqua latest (linux/amd64) to /home/tasato/.local/share/aquaproj-aqua/bin/aqua
```

It'd be also great if aqua-installer first tries to look for existing `aqua` cmd and if it's already latest then it skips installation.

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.

> Is it possible to show which version is going to be installed as well?

You can run `aqua -v` after running aqua-installer.

> It'd be also great if aqua-installer first tries to look for existing aqua cmd and if it's already latest then it skips installation.

https://github.com/aquaproj/aqua/issues/1041 seems to solve this issue.

**Comment by suzuki-shunsuke** [comment]
> > Is it possible to show which version is going to be installed as well?
> 
> How about running aqua -v after running aqua-installer?

https://github.com/aquaproj/aqua-installer/pull/169

**Comment by tadayosi** [comment]
Thanks, both enhancements look great!

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/aquaproj/aqua-installer/releases/tag/v1.1.2

**Comment by suzuki-shunsuke** [comment]
This issue has been solved.

- https://github.com/aquaproj/aqua-installer/releases/tag/v1.1.2
  - https://github.com/aquaproj/aqua-installer/pull/169
- https://github.com/aquaproj/aqua/releases/tag/v1.22.0
  - https://aquaproj.github.io/docs/tutorial-extras/update-aqua
  - https://github.com/aquaproj/aqua/issues/1041
