### ISSUE TITLE
Failed `go run github.com/aquaproj/aqua@latest`

### ISSUE THREAD

**Issue by s-takehana** [aquaproj/aqua-installer#305]
https://github.com/aquaproj/aqua-installer/blob/61e2563dfe7674cbf74fe6ec212e444198a3bb00/README.md?plain=1#L38-L42

It should be `go install github.com/aquaproj/aqua/cmd/aqua@latest` .

**Comment by suzuki-shunsuke** [comment]
Oh, nice catch! Thanks!
