### ISSUE TITLE
I want the hash of `v3.0.1`.

### ISSUE THREAD

**Issue by yasunori0418** [aquaproj/aqua-installer#640]
https://aquaproj.github.io/docs/products/aqua-installer#shell-script

The installation script hash of this repository introduced in the link above is for `v3.0.0`.
It would be helpful if you could publish the hash of `v3.0.1` on the release page and introduction page.

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.

I've added SHA256 checksums to GitHub Release pages.

e.g. https://github.com/aquaproj/aqua-installer/releases/tag/v3.0.1

<img width="881" alt="image" src="https://github.com/aquaproj/aqua-installer/assets/13323303/48616653-6cd0-4c7a-a415-b4c575706be2">
